[build]
build_commands = [
  [
    "docker", "build", "--build-arg", "LOCAL_PYPI_IP=$REGISTRY_IP",
    ".", "-t", "$REGISTRY_IP:5000/pve-cloud-controller:$VERSION"
  ],
  [
    "docker", "push", "$REGISTRY_IP:5000/pve-cloud-controller:$VERSION"
  ]
]
dyn_version_py_path = "src/pve_cloud_ctrl/_version.py"
sub_rebuild_keys = [ "version.py-pve-cloud" ]

[redis]
version_key = "version.pve-cloud-controller"